version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png
- url: /android
  static_dir: android
- url: /ios
  static_dir: ios
- url: /imessenger
  static_dir: imessenger
- url: /.*
  script: hpvball.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
