runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /tasks/.*
  script: hpsandvolleyball.app
  login: admin

- url: /admin
  script: hpsandvolleyball.app
  login: admin

- url: /ftolog
  script: hpsandvolleyball.app
  login: admin
  
- url: /.*
  script: hpsandvolleyball.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]